version: '3.0'

services:
  php-fpm:
    build: .dockerfiles/php
    restart: always
    container_name: php-url
    volumes:
      - .:/app
    working_dir: /app

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5439:5432
    volumes:
      - ./.dockerfiles/postgres/:/docker-entrypoint-initdb.d/

  web:
    image: nginx
    container_name: proxy
    volumes:
      - ./.dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 8088:80
    restart: always
    depends_on:
      - php-fpm
      - database

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./:/app
    command: composer install